spring:
  profiles:
    active: dev
  jackson:
    serialization:
      write_dates_as_timestamps: false
    date-format: yyyy-MM-dd'T'HH:mm:ss
app:
  constants:
    schedule:
      work-day-start-hour: 8
      work-day-end-hour: 18
      lesson:
        lesson-duration: 50
        break-between-lessons: 10
    calendar:
      amount-of-days: 30
      week-size: 6
