server:
  port: 8080
spring:
  flyway:
    locations: classpath:/db/migration/postgres
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/university
    username: postgres
    password: 1234
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
  jackson:
    serialization:
      write_dates_as_timestamps: false
    date-format: yyyy-MM-dd'T'HH:mm:ss
app:
  constants:
    calendar:
      amount-of-days: 30
      week-size: 6
    generator:
      amount-of-teachers: 40
      amount-of-students: 400
      amount-of-groups: 30
      amount-of-courses: 20
