server:
  port: 8080
spring:
  flyway:
    locations: classpath:/db/migration/postgres
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/university
    username: postgres
    password: 1234
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
